### ISSUE TITLE
FR: Reverse cycle order

### ISSUE THREAD

**Issue by acepelon** [houcheng/obsidian-cycle-in-sidebar-plugin#2]
First off, thank you for this!  I would love for this functionality to be part of the product itself.

Can you add a reverse cycle order so we can go back and forth between two of sidebar tabs instead of having to go all of the way through them?  You could make the reverse with hotkeys like
shift+ctl+[ 
shift+ctl+]
to mimic how other programs do the same kind of tab cycling.

Thanks!

**Comment by houcheng** [comment]
@acepelon 
It's a good idea and I've implemented this. 
Please try it by upgrading the plugin to 1.0.2,

Thank you for the suggestion~

**Comment by acepelon** [comment]
I tried installing 1.0.2 but it doesn't have a main.js in the repo.  I think I might not have the right instructions for installing the newer version.   Thanks!

**Comment by acepelon** [comment]
I was able to grab the 3 files from https://github.com/houcheng/obsidian-cycle-in-sidebar-plugin/releases and it works great.  It was a little unclear to the uninitiated, but all good now :)

**Comment by houcheng** [comment]
@acepelon 
Thank you~
