### ISSUE TITLE
Obsidian says ID mismatch

### ISSUE THREAD

**Issue by menagerie198** [houcheng/obsidian-cycle-in-sidebar-plugin#3]
Cant install this plugin - Obsidian says 'plugin ID mismatch'

**Comment by FelipeRearden** [comment]
Hello @houcheng 

I have the same issue :(

![9B0BE34E-BD2E-44E4-B3C4-11A281315F25](https://user-images.githubusercontent.com/85180696/217420893-7c3f4a8e-e428-4ac6-8c03-e4fd3b87985a.jpeg)

**Comment by WaterSibilantFalling** [comment]
Yup, and me. This is a showstopper.

**Comment by houcheng** [comment]
Hello @menagerie198 , @FelipeRearden , @WaterSibilantFalling,

Thank you a lot for using this plugin. 
Sorry for late to see the issue. I can reproduce this issue now and am looking into this.
My plugin-id in manifest seems the same as community-plugins.json in obsidian-release. 
Maybe need to bump to a newer version for obsidian can drop the old/ wrong manifest.

**Comment by houcheng** [comment]
Issue fixed.
