### ISSUE TITLE
[Bug] Split side panel breaks the function

### ISSUE THREAD

**Issue by Osten** [houcheng/obsidian-cycle-in-sidebar-plugin#6]
If the sidebar contains several panes (I use split down for google calendar plugin) it no longer cycles, only travels forward until it reaches the end.

Thanks!

**Comment by houcheng** [comment]
@Osten can you show me more detail on your configuration or how to set the panel "split down". I tried the cycling with latest feature and 4 tabs on the right panel, seems okay. Thank you.

![image](https://github.com/user-attachments/assets/6e8828c2-5ab9-4a38-9944-8a973cc97591)

**Comment by Jaschenn** [comment]
i found the same error, here is my config:

<img width="439" alt="image" src="https://github.com/user-attachments/assets/74dd8b8b-c05e-489b-8b9c-011df51f3f70">

when i use cmd+[ and cmd + ] to change active tab in right sidebar, it always cycle in each icon in top panel and the start/end icon in down panel. here's a video to help you understand:


https://github.com/user-attachments/assets/f3d4bf9e-2d95-4a0b-8cba-f32f33022120

**Comment by houcheng** [comment]
@Jaschenn 
Hi, thanks for the information.
I've updated the fixed 1.0.3.
Thanks~
